const $=id=>document.getElementById(id);
const el={lineProfileName:$('lineProfileName'),launchMode:$('launchMode'),coachNameInline:$('coachNameInline'),coachNameInput:$('coachNameInput'),coachStatePill:$('coachStatePill'),coachWidgetStatus:$('coachWidgetStatus'),monitoringText:$('monitoringText'),monitoringSubText:$('monitoringSubText'),teacherAlertText:$('teacherAlertText'),surveillanceBannerText:$('surveillanceBannerText'),watchState:$('watchState'),coachMessageState:$('coachMessageState'),sessionType:$('sessionType'),focusMessage:$('focusMessage'),goalMinutesSelect:$('goalMinutesSelect'),breakMinutesSelect:$('breakMinutesSelect'),nextGoalInput:$('nextGoalInput'),saveNextGoalBtn:$('saveNextGoalBtn'),taskTitleInput:$('taskTitleInput'),taskGoalInput:$('taskGoalInput'),taskEstimateSelect:$('taskEstimateSelect'),taskPrioritySelect:$('taskPrioritySelect'),taskMemoInput:$('taskMemoInput'),addTaskBtn:$('addTaskBtn'),taskManagerList:$('taskManagerList'),taskOverviewList:$('taskOverviewList'),taskSummaryCount:$('taskSummaryCount'),taskTabListBtn:$('taskTabListBtn'),taskTabAddBtn:$('taskTabAddBtn'),taskTabList:$('taskTabList'),taskTabAdd:$('taskTabAdd'),selfVideoThumb:$('selfVideoThumb'),selfVideoMain:$('selfVideoMain'),cameraStatus:$('cameraStatus'),hiddenOverlay:$('hiddenOverlay'),startBtn:$('startBtn'),toggleCamBtn:$('toggleCamBtn'),pauseTimerBtn:$('pauseTimerBtn'),breakBtn:$('breakBtn'),endBreakBtn:$('endBreakBtn'),nextMsgBtn:$('nextMsgBtn'),restartSessionBtn:$('restartSessionBtn'),wakeLockBtn:$('wakeLockBtn'),fullscreenBtn:$('fullscreenBtn'),leaveBtn:$('leaveBtn'),soundModeSelect:$('soundModeSelect'),soundVolumeRange:$('soundVolumeRange'),soundToggleBtn:$('soundToggleBtn'),elapsedTimeEl:$('elapsedTime'),goalTimerEl:$('goalTimer'),blurCountEl:$('blurCount'),dailyTotalEl:$('dailyTotal'),focusScoreEl:$('focusScore'),completionRateEl:$('completionRate'),streakDaysEl:$('streakDays'),dailyComparisonEl:$('dailyComparison'),weeklyTotalEl:$('weeklyTotal'),breakCountEl:$('breakCount'),pauseCountEl:$('pauseCount'),camOffTimeEl:$('camOffTime'),activeTaskName:$('activeTaskName'),activeTaskMeta:$('activeTaskMeta'),reportModal:$('reportModal'),reportBody:$('reportBody'),closeReportBtn:$('closeReportBtn'),copyReportBtn:$('copyReportBtn'),historyModal:$('historyModal'),historyBody:$('historyBody'),openHistoryBtn:$('openHistoryBtn'),closeHistoryBtn:$('closeHistoryBtn'),exportLogsBtn:$('exportLogsBtn'),screenHome:$('screenHome'),screenTasks:$('screenTasks'),screenRoom:$('screenRoom'),screenSettings:$('screenSettings'),tabHomeBtn:$('tabHomeBtn'),tabTasksBtn:$('tabTasksBtn'),tabRoomBtn:$('tabRoomBtn'),tabSettingsBtn:$('tabSettingsBtn'),userWidget:$('userWidget'),userWidgetHandle:$('userWidgetHandle')};
const APP_CONFIG=window.APP_CONFIG||{}; const LIFF_ID=APP_CONFIG.LIFF_ID||""; const ALLOW_NON_LIFF_MODE=APP_CONFIG.ALLOW_NON_LIFF_MODE!==false;
const S={coach:'focus-room-v13-coach-name',goal:'focus-room-v13-goal-minutes',brk:'focus-room-v13-break-minutes',next:'focus-room-v13-next-goal',tasks:'focus-room-v13-tasks',activeTaskTab:'focus-room-v13-active-task-tab',activeScreen:'focus-room-v13-active-screen',userPos:'focus-room-v13-user-widget-pos',sessions:'focus-room-v13-sessions',weekly:'focus-room-v13-weekly-logs',draftTitle:'focus-room-v13-draft-title',draftGoal:'focus-room-v13-draft-goal',draftMemo:'focus-room-v13-draft-memo',draftEst:'focus-room-v13-draft-estimate',draftPrio:'focus-room-v13-draft-priority'};
let tasks=[],selectedGoalMinutes=25,selectedBreakMinutes=5,stream=null,camEnabled=true,wakeLock=null,sessionStartedAt=null,elapsedInterval=null,timerInterval=null,messageInterval=null,monitorInterval=null,camOffInterval=null,blurCount=0,pauseCount=0,breakCount=0,camOffSeconds=0,timerPaused=false,onBreak=false,remainingSeconds=25*60,breakRemaining=0,activeTaskTab='list',activeScreen='home',currentSessionLog=null,audioContext=null,noiseNode=null,gainNode=null,toneOscillator=null;
const roomMessages=['今のタスクを1つだけ進めましょう。','机に戻ったら、そのまま30秒だけ続けましょう。','迷ったら、いちばん小さい作業から始めましょう。','いま進めるべきタスクを1件だけ選んで集中しましょう。','完璧より前進です。今日の目標を少しでも進めましょう。'];
const monitorTexts=['在席確認中','学習状況監視中','視線確認中','離席警戒中'];
const subMonitorTexts=['離席検知 有効','画面切替 検知中','カメラ監視 有効','集中確認 有効'];
const teacherAlerts=['このルームでは離席・画面切替・学習停止を前提に確認しながら進行します。今のタスクに集中してください。','姿勢が崩れないようにして、このまま画面を前面に保ってください。','手が止まっているなら、まずは1問・1ページだけ進めてください。','このセッション中は在席前提で進みます。今の学習を継続してください。'];
const bannerTexts=['このルームは在席確認つきで進行しています','離席検知と学習確認を前提に進行しています','監視前提の集中ルームです。画面を前面に保ってください'];
const priorityOrder={'高':0,'中':1,'低':2};
const jset=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const jget=(k,d)=>{try{const r=localStorage.getItem(k);return r===null?d:JSON.parse(r)}catch{return d}};
const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2,8)}`;
const fmtClock=s=>`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const fmtMinSec=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const tkey=(o=0)=>{const d=new Date();d.setDate(d.getDate()+o);return d.toISOString().slice(0,10)};
const rand=a=>a[Math.floor(Math.random()*a.length)];
const esc=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#039;");
function setText(n,t){n.textContent=t}
function updateMessage(force=false,txt=""){setText(el.focusMessage,txt||rand(roomMessages));if(force)el.focusMessage.animate([{opacity:.2,transform:'translateY(4px)'},{opacity:1,transform:'translateY(0)'}],{duration:280,easing:'ease-out'})}
function saveDailyTotal(sec){localStorage.setItem(`focus-room-total-${tkey()}`,String(sec));const m=Math.floor(sec/60),h=String(Math.floor(m/60)).padStart(2,'0'),mm=String(m%60).padStart(2,'0');setText(el.dailyTotalEl,`${h}:${mm}`)}
function loadDailyTotal(key=tkey()){const raw=localStorage.getItem(`focus-room-total-${key}`);return raw?Number(raw):0}
function updateWeeklyStats(){const logs=jget(S.weekly,{}),days=Array.from({length:7},(_,i)=>tkey(-i)),total=days.reduce((s,k)=>s+(logs[k]?.minutes||0),0);setText(el.weeklyTotalEl,`${total}分`);const diff=Math.round((loadDailyTotal(tkey())-loadDailyTotal(tkey(-1)))/60);setText(el.dailyComparisonEl,`${diff>=0?'+':''}${diff}分`);let streak=0;for(let i=0;i<30;i++){if((logs[tkey(-i)]?.minutes||0)>0)streak++;else break}setText(el.streakDaysEl,`${streak}日`)}
function recordWeekly(){const logs=jget(S.weekly,{});logs[tkey()]={minutes:Math.round(loadDailyTotal()/60),updatedAt:Date.now()};jset(S.weekly,logs);updateWeeklyStats()}
function updateScore(){let score=100-blurCount*8-pauseCount*5-breakCount*3-Math.floor(camOffSeconds/30)*4;score=Math.max(0,Math.min(100,score));setText(el.focusScoreEl,String(score))}
function updateCountersUI(){setText(el.breakCountEl,String(breakCount));setText(el.pauseCountEl,String(pauseCount));setText(el.camOffTimeEl,`${camOffSeconds}秒`);setText(el.blurCountEl,String(blurCount));updateScore()}
function sortTasks(list){return [...list].sort((a,b)=>{if(a.status==='進行中'&&b.status!=='進行中')return -1;if(a.status!=='進行中'&&b.status==='進行中')return 1;if(a.status==='完了'&&b.status!=='完了')return 1;if(a.status!=='完了'&&b.status==='完了')return -1;if(priorityOrder[a.priority]!==priorityOrder[b.priority])return priorityOrder[a.priority]-priorityOrder[b.priority];return a.createdAt-b.createdAt})}
function getActiveTask(){return sortTasks(tasks).find(t=>t.status==='進行中')||null}
function completionRate(){return tasks.length?Math.round(tasks.filter(t=>t.status==='完了').length/tasks.length*100):0}
function updateActiveTaskBox(){const t=getActiveTask();if(!t){setText(el.activeTaskName,'まだありません');setText(el.activeTaskMeta,'タスクを追加して進行中にするとここに固定表示されます。');return}setText(el.activeTaskName,t.title);setText(el.activeTaskMeta,`予定時間 ${t.estimate}分 / 優先度 ${t.priority} / 目標 ${t.goal}`)}
function taskHtml(t){return `<div class="task-item"><div class="task-item-top"><div><div class="task-title">${esc(t.title)}</div><div class="task-meta">目標：${esc(t.goal)}</div><div class="task-extra">予定時間：${t.estimate}分 / 優先度：${esc(t.priority)}</div><div class="task-note">メモ：${esc(t.memo)}</div></div><span class="task-chip">${esc(t.status)}</span></div><div class="task-actions"><button class="btn btn-secondary" data-action="todo" data-id="${t.id}">未開始</button><button class="btn btn-secondary" data-action="doing" data-id="${t.id}">進行中</button><button class="btn btn-secondary" data-action="done" data-id="${t.id}">完了</button><button class="btn btn-secondary" data-action="delete" data-id="${t.id}">削除</button></div></div>`}
function renderTasks(){const sorted=sortTasks(tasks);setText(el.taskSummaryCount,`${tasks.length}件`);setText(el.completionRateEl,`${completionRate()}%`);updateActiveTaskBox();if(!sorted.length){const empty='<p class="empty-text">追加したタスクはここに表示されます。</p>';el.taskManagerList.innerHTML=empty;el.taskOverviewList.innerHTML=empty;return}const html=sorted.map(taskHtml).join('');el.taskManagerList.innerHTML=html;el.taskOverviewList.innerHTML=html}
function saveTasks(){jset(S.tasks,tasks);renderTasks()}
function addTask(){const title=el.taskTitleInput.value.trim();if(!title){alert('タスク名を入力してください。');return}tasks.push({id:uid(),title,goal:el.taskGoalInput.value.trim()||'未設定',memo:el.taskMemoInput.value.trim()||'未設定',estimate:Number(el.taskEstimateSelect.value||30),priority:el.taskPrioritySelect.value||'高',status:'未開始',createdAt:Date.now()});saveTasks();updateMessage(true,`「${title}」を追加しました。`);el.taskTitleInput.value='';el.taskGoalInput.value='';el.taskMemoInput.value='';el.taskEstimateSelect.value='30';el.taskPrioritySelect.value='高';saveDrafts();openTaskTab('list')}
function updateTaskStatus(id,status){tasks=tasks.map(t=>t.id===id?{...t,status}:t);saveTasks();const t=tasks.find(x=>x.id===id);if(t)updateMessage(true,`「${t.title}」を${status}にしました。`)}
function deleteTask(id){const t=tasks.find(x=>x.id===id);tasks=tasks.filter(x=>x.id!==id);saveTasks();if(t)updateMessage(true,`「${t.title}」を削除しました。`)}
function saveDrafts(){jset(S.draftTitle,el.taskTitleInput.value.trim());jset(S.draftGoal,el.taskGoalInput.value.trim());jset(S.draftMemo,el.taskMemoInput.value.trim());jset(S.draftEst,el.taskEstimateSelect.value);jset(S.draftPrio,el.taskPrioritySelect.value)}
function applyScreen(){const m={home:[el.screenHome,el.tabHomeBtn],tasks:[el.screenTasks,el.tabTasksBtn],room:[el.screenRoom,el.tabRoomBtn],settings:[el.screenSettings,el.tabSettingsBtn]};Object.entries(m).forEach(([k,[s,b]])=>{const a=k===activeScreen;s.classList.toggle('active',a);b.classList.toggle('active',a)});jset(S.activeScreen,activeScreen)}
function openScreen(n){activeScreen=n;applyScreen()}
function applyTaskTab(){const list=activeTaskTab==='list';el.taskTabListBtn.classList.toggle('active',list);el.taskTabAddBtn.classList.toggle('active',!list);el.taskTabList.classList.toggle('active',list);el.taskTabAdd.classList.toggle('active',!list);jset(S.activeTaskTab,activeTaskTab)}
function openTaskTab(n){activeTaskTab=n;applyTaskTab()}
function applyCoachName(save=true){const name=el.coachNameInput.value.trim()||'SENSEI ROOM';setText(el.coachNameInline,name);if(save)jset(S.coach,name)}
function applyGoalMinutes(save=true){selectedGoalMinutes=Number(el.goalMinutesSelect.value||25);if(save)jset(S.goal,selectedGoalMinutes);if(!onBreak){remainingSeconds=selectedGoalMinutes*60;setText(el.goalTimerEl,fmtMinSec(remainingSeconds));if(!stream)setText(el.sessionType,'未開始')}}
function applyBreakMinutes(save=true){selectedBreakMinutes=Number(el.breakMinutesSelect.value||5);if(save)jset(S.brk,selectedBreakMinutes)}
function clearTimers(){clearInterval(elapsedInterval);clearInterval(timerInterval);clearInterval(messageInterval);clearInterval(monitorInterval);clearInterval(camOffInterval)}
function setButtons(started){el.toggleCamBtn.disabled=!started;el.pauseTimerBtn.disabled=!started;el.breakBtn.disabled=!started||onBreak;el.endBreakBtn.disabled=!started||!onBreak}
function startMonitorEffects(){clearInterval(monitorInterval);monitorInterval=setInterval(()=>{setText(el.monitoringText,rand(monitorTexts));setText(el.monitoringSubText,rand(subMonitorTexts));setText(el.teacherAlertText,rand(teacherAlerts));setText(el.surveillanceBannerText,rand(bannerTexts));},8000)}
function startCamOffCounter(){clearInterval(camOffInterval);camOffInterval=setInterval(()=>{if(stream&&!camEnabled){camOffSeconds+=1;updateCountersUI()}},1000)}
function beginSessionLog(){currentSessionLog={id:uid(),startedAt:new Date().toISOString(),goalMinutes:selectedGoalMinutes,nextGoal:el.nextGoalInput.value.trim()||'',blurCount:0,pauseCount:0,breakCount:0,camOffSeconds:0,tasks:tasks.map(t=>({title:t.title,status:t.status,estimate:t.estimate,priority:t.priority}))}}
function finalizeSessionLog(){if(!currentSessionLog)return null;Object.assign(currentSessionLog,{endedAt:new Date().toISOString(),dailyTotalMinutes:Math.round(loadDailyTotal()/60),blurCount,pauseCount,breakCount,camOffSeconds,focusScore:Number(el.focusScoreEl.textContent||'0'),completionRate:completionRate(),tasks:tasks.map(t=>({title:t.title,status:t.status,estimate:t.estimate,priority:t.priority}))});const arr=jget(S.sessions,[]);arr.unshift(currentSessionLog);jset(S.sessions,arr.slice(0,50));return currentSessionLog}
function renderReport(log){if(!log)return;const done=log.tasks.filter(t=>t.status==='完了').length;el.reportBody.innerHTML=`<div class="report-item"><strong>集中スコア</strong><div>${log.focusScore}</div></div><div class="report-item"><strong>達成率</strong><div>${log.completionRate}%（完了 ${done}/${log.tasks.length}）</div></div><div class="report-item"><strong>離席 / 停止 / 休憩</strong><div>離席 ${log.blurCount}回 / 停止 ${log.pauseCount}回 / 休憩 ${log.breakCount}回</div></div><div class="report-item"><strong>カメラ停止時間</strong><div>${log.camOffSeconds}秒</div></div><div class="report-item"><strong>次回目標</strong><div>${esc(log.nextGoal||'未設定')}</div></div>`;el.reportModal.classList.remove('hidden')}
function renderHistory(){const arr=jget(S.sessions,[]);el.historyBody.innerHTML=arr.length?arr.map(s=>`<div class="history-item"><strong>${new Date(s.startedAt).toLocaleString('ja-JP')}</strong><div>集中スコア ${s.focusScore} / 達成率 ${s.completionRate}% / 離席 ${s.blurCount}回</div></div>`).join(''):'<p class="empty-text">履歴はまだありません。</p>';el.historyModal.classList.remove('hidden')}
function exportLogs(){const data={sessions:jget(S.sessions,[]),weekly:jget(S.weekly,{}),tasks};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='focus-room-log.json';a.click();URL.revokeObjectURL(a.href)}
async function ensureAudio(){if(!audioContext){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)throw new Error('AudioContext unsupported');audioContext=new Ctx()}if(audioContext.state==='suspended')await audioContext.resume()}
function createNoiseBuffer(ctx,type='white'){const size=2*ctx.sampleRate,b=ctx.createBuffer(1,size,ctx.sampleRate),out=b.getChannelData(0);let last=0;for(let i=0;i<size;i++){const white=Math.random()*2-1;if(type==='brown'){out[i]=(last+0.02*white)/1.02;last=out[i];out[i]*=3.5}else out[i]=white}return b}
async function toggleSound(){const mode=el.soundModeSelect.value;if(mode==='off'){stopSound();return}if(noiseNode||toneOscillator){stopSound();return}await ensureAudio();gainNode=audioContext.createGain();gainNode.gain.value=Number(el.soundVolumeRange.value)/1000;gainNode.connect(audioContext.destination);if(mode==='tone'){toneOscillator=audioContext.createOscillator();toneOscillator.type='sine';toneOscillator.frequency.value=180;toneOscillator.connect(gainNode);toneOscillator.start()}else{noiseNode=audioContext.createBufferSource();noiseNode.buffer=createNoiseBuffer(audioContext,mode);noiseNode.loop=true;noiseNode.connect(gainNode);noiseNode.start()}setText(el.soundToggleBtn,'サウンド停止')}
function stopSound(){try{noiseNode?.stop?.()}catch{}try{toneOscillator?.stop?.()}catch{}noiseNode=null;toneOscillator=null;gainNode?.disconnect?.();gainNode=null;setText(el.soundToggleBtn,'サウンド開始')}
function updateSoundVolume(){if(gainNode)gainNode.gain.value=Number(el.soundVolumeRange.value)/1000}
function playNotification(){try{const ctx=audioContext||new (window.AudioContext||window.webkitAudioContext)();audioContext=ctx;const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=880;g.gain.value=.02;o.start();o.stop(ctx.currentTime+.2)}catch{}}
function startRoomTimers(reset=true){clearTimers();if(reset||!sessionStartedAt)sessionStartedAt=Date.now();timerPaused=false;setText(el.pauseTimerBtn,'タイマー一時停止');const baseline=loadDailyTotal();saveDailyTotal(baseline);elapsedInterval=setInterval(()=>{if(timerPaused)return;const e=Math.floor((Date.now()-sessionStartedAt)/1000);setText(el.elapsedTimeEl,fmtClock(e));if(!onBreak){saveDailyTotal(baseline+e);recordWeekly()}},1000);timerInterval=setInterval(()=>{if(timerPaused)return;if(onBreak){breakRemaining-=1;setText(el.goalTimerEl,fmtMinSec(breakRemaining));if(breakRemaining<=0){playNotification();endBreak()}return}remainingSeconds-=1;setText(el.goalTimerEl,fmtMinSec(remainingSeconds));if(remainingSeconds<=0){remainingSeconds=0;setText(el.goalTimerEl,fmtMinSec(remainingSeconds));setText(el.sessionType,'目標時間に到達');setText(el.coachWidgetStatus,'学習時間に到達');setText(el.monitoringText,'確認強化中');setText(el.teacherAlertText,'目標時間に到達しました。離席せず、タスクの進み具合を確認してください。');setText(el.surveillanceBannerText,'学習時間到達後も在席確認を継続しています');updateMessage(true,'目標時間に到達しました。タスクの進み具合を確認しましょう。')}},1000);messageInterval=setInterval(()=>{if(!timerPaused)updateMessage(true)},60000);startMonitorEffects();startCamOffCounter()}
async function startCamera(){if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){alert('このブラウザではカメラ取得に対応していません。');return}if(!tasks.length){alert('先にタスクを1件以上追加してください。');openScreen('tasks');openTaskTab('add');return}applyCoachName();applyGoalMinutes();applyBreakMinutes();beginSessionLog();try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});el.selfVideoThumb.srcObject=stream;el.selfVideoMain.srcObject=stream;setText(el.cameraStatus,'稼働中');setText(el.watchState,'入室中');setText(el.coachMessageState,'表示中');setText(el.coachStatePill,'監視中');setText(el.sessionType,`${selectedGoalMinutes}分の学習中`);setText(el.coachWidgetStatus,'学習状況をリアルタイムで確認しています');setText(el.monitoringText,'在席確認中');setText(el.monitoringSubText,'離席検知 有効');setText(el.teacherAlertText,'このルームでは離席・画面切替・学習停止を前提に確認しながら進行します。今のタスクに集中してください。');setText(el.surveillanceBannerText,'このルームは在席確認つきで進行しています');el.startBtn.disabled=true;setButtons(true);camEnabled=true;setText(el.toggleCamBtn,'カメラ停止');onBreak=false;remainingSeconds=selectedGoalMinutes*60;setText(el.goalTimerEl,fmtMinSec(remainingSeconds));const first=sortTasks(tasks).find(t=>t.status==='未開始');if(first)updateTaskStatus(first.id,'進行中');startRoomTimers(true);updateMessage(true,'入室しました。今日のタスクを順番に進めましょう。');openScreen('home')}catch(e){console.error(e);alert('カメラ許可が必要です。ブラウザの権限を確認してください。')}}
function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());el.selfVideoThumb.srcObject=null;el.selfVideoMain.srcObject=null;stream=null;setText(el.cameraStatus,'待機中');setText(el.watchState,'待機中');setText(el.coachMessageState,'表示中');setText(el.coachStatePill,'接続中');setText(el.sessionType,'未開始');setText(el.coachWidgetStatus,'ルーム待機中');setText(el.monitoringText,'在席確認前');setText(el.monitoringSubText,'離席検知 有効');setText(el.teacherAlertText,'目標時間を設定して、今日のタスクを追加してから入室してください。');setText(el.surveillanceBannerText,'このルームは在席確認つきで進行しています');el.startBtn.disabled=false;setButtons(false);el.breakBtn.disabled=true;el.endBreakBtn.disabled=true;onBreak=false;clearTimers();const log=finalizeSessionLog();if(log)renderReport(log)}
function toggleCameraEnabled(){if(!stream)return;const track=stream.getVideoTracks()[0];if(!track)return;camEnabled=!camEnabled;track.enabled=camEnabled;setText(el.toggleCamBtn,camEnabled?'カメラ停止':'カメラ再開');setText(el.cameraStatus,camEnabled?'稼働中':'一時停止');setText(el.monitoringText,camEnabled?'映像確認中':'映像停止中');setText(el.monitoringSubText,camEnabled?'離席検知 有効':'映像停止 記録中')}
function toggleTimerPause(){if(!stream)return;timerPaused=!timerPaused;pauseCount+=1;setText(el.pauseTimerBtn,timerPaused?'タイマー再開':'タイマー一時停止');setText(el.coachMessageState,timerPaused?'停止中':'表示中');setText(el.coachWidgetStatus,timerPaused?'一時停止中':'学習状況をリアルタイムで確認しています');setText(el.monitoringText,timerPaused?'確認待機中':'在席確認中');updateCountersUI();updateMessage(true,timerPaused?'タイマーを一時停止しました。':'タイマーを再開しました。')}
function startBreak(){if(!stream||onBreak)return;onBreak=true;breakCount+=1;breakRemaining=selectedBreakMinutes*60;setText(el.sessionType,'休憩中');el.breakBtn.disabled=true;el.endBreakBtn.disabled=false;setText(el.coachWidgetStatus,'休憩中');setText(el.monitoringText,'休憩確認中');setText(el.teacherAlertText,'休憩中です。戻ったらすぐに学習を再開してください。');setText(el.surveillanceBannerText,'休憩中も在席状態の確認を継続しています');updateCountersUI();playNotification();updateMessage(true,'休憩に入りました。戻ったら「休憩終了」を押してください。')}
function endBreak(){if(!stream||!onBreak)return;onBreak=false;setText(el.sessionType,`${selectedGoalMinutes}分の学習中`);el.breakBtn.disabled=false;el.endBreakBtn.disabled=true;setText(el.coachWidgetStatus,'学習状況をリアルタイムで確認しています');setText(el.monitoringText,'在席確認中');setText(el.teacherAlertText,'休憩終了です。姿勢と視線を整えて学習を再開してください。');setText(el.surveillanceBannerText,'このルームは在席確認つきで進行しています');playNotification();updateMessage(true,'休憩を終了しました。学習を再開しましょう。')}
function restartSessionFromSettings(){applyCoachName();applyGoalMinutes();applyBreakMinutes();setText(el.elapsedTimeEl,'00:00:00');sessionStartedAt=Date.now();onBreak=false;el.breakBtn.disabled=!stream;el.endBreakBtn.disabled=true;remainingSeconds=selectedGoalMinutes*60;setText(el.goalTimerEl,fmtMinSec(remainingSeconds));if(stream){setText(el.sessionType,`${selectedGoalMinutes}分の学習中`);setText(el.coachWidgetStatus,'学習状況をリアルタイムで確認しています');setText(el.monitoringText,'在席確認中');setText(el.teacherAlertText,'設定を更新しました。このまま学習を継続してください。');startRoomTimers(true);updateMessage(true,'設定内容でセッションを再開始しました。')}else{setText(el.sessionType,'未開始');setText(el.coachWidgetStatus,'ルーム待機中');updateMessage(true,'設定を更新しました。')}}
async function requestFullscreen(){if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();else await document.exitFullscreen?.()}
async function requestWakeLock(){if(!('wakeLock' in navigator)){alert('この端末では画面スリープ防止に未対応です。');return}try{wakeLock=await navigator.wakeLock.request('screen');setText(el.wakeLockBtn,'スリープ防止中');wakeLock.addEventListener('release',()=>setText(el.wakeLockBtn,'画面スリープ防止'))}catch(e){console.error(e);alert('画面スリープ防止を有効にできませんでした。')}}
async function initLiffApp(){if(!window.liff||!LIFF_ID){setText(el.lineProfileName,'通常ブラウザで利用中');setText(el.launchMode,'通常ブラウザ');return}try{await liff.init({liffId:LIFF_ID});setText(el.launchMode,liff.isInClient()?'LINE内ブラウザ':'外部ブラウザ');if(!liff.isLoggedIn()){if(ALLOW_NON_LIFF_MODE){setText(el.lineProfileName,'ログインなしで利用中');return}liff.login();return}const p=await liff.getProfile();setText(el.lineProfileName,`${p.displayName} さん`)}catch(e){console.error(e);setText(el.lineProfileName,'ユーザー情報の取得に失敗しました')}}
function clamp(v,min,max){return Math.min(Math.max(v,min),max)}
function applyUserWidgetPosition(x,y,save=true){const margin=10,maxX=window.innerWidth-el.userWidget.offsetWidth-margin,maxY=window.innerHeight-el.userWidget.offsetHeight-margin,fx=clamp(x,margin,maxX),fy=clamp(y,margin,maxY);el.userWidget.style.left=`${fx}px`;el.userWidget.style.top=`${fy}px`;el.userWidget.style.right='auto';if(save)jset(S.userPos,{x:fx,y:fy})}
function restoreUserWidgetPosition(){const saved=jget(S.userPos,null);if(saved&&typeof saved.x==='number'&&typeof saved.y==='number')applyUserWidgetPosition(saved.x,saved.y,false);else applyUserWidgetPosition(window.innerWidth-el.userWidget.offsetWidth-14,14,false)}
function initDragWidget(){let startX=0,startY=0,originX=0,originY=0,dragging=false;const move=e=>{if(!dragging)return;applyUserWidgetPosition(originX+(e.clientX-startX),originY+(e.clientY-startY),false)};const up=()=>{if(!dragging)return;dragging=false;const r=el.userWidget.getBoundingClientRect();const tx=r.left<window.innerWidth/2?10:window.innerWidth-r.width-10;applyUserWidgetPosition(tx,r.top,true);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};el.userWidgetHandle.addEventListener('pointerdown',e=>{dragging=true;startX=e.clientX;startY=e.clientY;const r=el.userWidget.getBoundingClientRect();originX=r.left;originY=r.top;window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)})}
document.addEventListener('visibilitychange',()=>{if(document.hidden){blurCount+=1;updateCountersUI();el.hiddenOverlay.classList.remove('hidden');setText(el.monitoringText,'離席検知');setText(el.monitoringSubText,'警告表示中');setText(el.teacherAlertText,'画面から離れています。すぐに戻って学習を再開してください。');setText(el.surveillanceBannerText,'離席検知中です。画面へ戻ってください');updateMessage(true,'この画面に戻って、そのまま学習を続けましょう。')}else{el.hiddenOverlay.classList.add('hidden');if(stream&&!timerPaused&&!onBreak){setText(el.monitoringText,'在席確認中');setText(el.monitoringSubText,'離席検知 有効')}}});
document.addEventListener('visibilitychange',async()=>{if(wakeLock!==null&&document.visibilityState==='visible'){try{wakeLock=await navigator.wakeLock.request('screen')}catch(e){console.error(e)}}});
document.addEventListener('fullscreenchange',()=>setText(el.fullscreenBtn,document.fullscreenElement?'フルスクリーン解除':'フルスクリーン'));
window.addEventListener('beforeunload',e=>{if(stream){e.preventDefault();e.returnValue=''}});
window.addEventListener('resize',()=>{const r=el.userWidget.getBoundingClientRect();applyUserWidgetPosition(r.left,r.top,true)});
el.tabHomeBtn.addEventListener('click',()=>openScreen('home'));el.tabTasksBtn.addEventListener('click',()=>openScreen('tasks'));el.tabRoomBtn.addEventListener('click',()=>openScreen('room'));el.tabSettingsBtn.addEventListener('click',()=>openScreen('settings'));el.taskTabListBtn.addEventListener('click',()=>openTaskTab('list'));el.taskTabAddBtn.addEventListener('click',()=>openTaskTab('add'));el.addTaskBtn.addEventListener('click',addTask);el.taskTitleInput.addEventListener('input',saveDrafts);el.taskGoalInput.addEventListener('input',saveDrafts);el.taskEstimateSelect.addEventListener('change',saveDrafts);el.taskPrioritySelect.addEventListener('change',saveDrafts);el.taskMemoInput.addEventListener('input',saveDrafts);el.goalMinutesSelect.addEventListener('change',()=>applyGoalMinutes(true));el.breakMinutesSelect.addEventListener('change',()=>applyBreakMinutes(true));el.coachNameInput.addEventListener('input',()=>applyCoachName(true));el.saveNextGoalBtn.addEventListener('click',()=>{jset(S.next,el.nextGoalInput.value.trim());alert('次回目標を保存しました。')});el.openHistoryBtn.addEventListener('click',renderHistory);el.closeHistoryBtn.addEventListener('click',()=>el.historyModal.classList.add('hidden'));el.exportLogsBtn.addEventListener('click',exportLogs);el.closeReportBtn.addEventListener('click',()=>el.reportModal.classList.add('hidden'));el.copyReportBtn.addEventListener('click',async()=>{await navigator.clipboard.writeText(el.reportBody.innerText);alert('レポートをコピーしました。')});el.soundToggleBtn.addEventListener('click',toggleSound);el.soundVolumeRange.addEventListener('input',updateSoundVolume);el.soundModeSelect.addEventListener('change',stopSound);el.startBtn.addEventListener('click',startCamera);el.toggleCamBtn.addEventListener('click',toggleCameraEnabled);el.pauseTimerBtn.addEventListener('click',toggleTimerPause);el.breakBtn.addEventListener('click',startBreak);el.endBreakBtn.addEventListener('click',endBreak);el.nextMsgBtn.addEventListener('click',()=>{setText(el.teacherAlertText,rand(teacherAlerts));setText(el.surveillanceBannerText,rand(bannerTexts));updateMessage(true)});el.restartSessionBtn.addEventListener('click',restartSessionFromSettings);el.wakeLockBtn.addEventListener('click',requestWakeLock);el.fullscreenBtn.addEventListener('click',requestFullscreen);el.leaveBtn.addEventListener('click',()=>{stopCamera();if(document.fullscreenElement)document.exitFullscreen?.();alert('退出しました。おつかれさまでした。')});
function bindTaskActions(node){node.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const id=b.dataset.id,action=b.dataset.action;if(action==='todo')updateTaskStatus(id,'未開始');if(action==='doing')updateTaskStatus(id,'進行中');if(action==='done')updateTaskStatus(id,'完了');if(action==='delete')deleteTask(id)})}
window.addEventListener('DOMContentLoaded',async()=>{tasks=jget(S.tasks,[]);activeTaskTab=jget(S.activeTaskTab,'list');activeScreen=jget(S.activeScreen,'home');el.coachNameInput.value=jget(S.coach,'SENSEI ROOM');el.goalMinutesSelect.value=String(jget(S.goal,25));el.breakMinutesSelect.value=String(jget(S.brk,5));el.nextGoalInput.value=jget(S.next,'');el.taskTitleInput.value=jget(S.draftTitle,'');el.taskGoalInput.value=jget(S.draftGoal,'');el.taskMemoInput.value=jget(S.draftMemo,'');el.taskEstimateSelect.value=jget(S.draftEst,'30');el.taskPrioritySelect.value=jget(S.draftPrio,'高');saveDailyTotal(loadDailyTotal());applyCoachName(false);applyGoalMinutes(false);applyBreakMinutes(false);renderTasks();bindTaskActions(el.taskManagerList);bindTaskActions(el.taskOverviewList);setButtons(false);el.breakBtn.disabled=true;el.endBreakBtn.disabled=true;applyTaskTab();applyScreen();restoreUserWidgetPosition();initDragWidget();updateWeeklyStats();updateCountersUI();setText(el.coachWidgetStatus,'学習状況をリアルタイムで確認しています');setText(el.monitoringText,'在席確認前');setText(el.monitoringSubText,'離席検知 有効');setText(el.teacherAlertText,'このルームでは離席・画面切替・学習停止を前提に確認しながら進行します。今のタスクに集中してください。');setText(el.surveillanceBannerText,'このルームは在席確認つきで進行しています');await initLiffApp()});
