
const $=(id)=>document.getElementById(id);
const prejoinScreen=$('prejoinScreen'),roomScreen=$('roomScreen'),userWidget=$('userWidget'),userWidgetHandle=$('userWidgetHandle');
const lineProfileName=$('lineProfileName'),goalMinutesSelect=$('goalMinutesSelect'),breakMinutesSelect=$('breakMinutesSelect'),coachNameInput=$('coachNameInput');
const prejoinGoalLabel=$('prejoinGoalLabel'),prejoinTaskCount=$('prejoinTaskCount');
const taskSummaryCount=$('taskSummaryCount'),prejoinTaskList=$('prejoinTaskList'),roomTaskList=$('roomTaskList'),roomTaskCount=$('roomTaskCount');
const taskTitleInput=$('taskTitleInput'),taskGoalInput=$('taskGoalInput'),taskEstimateSelect=$('taskEstimateSelect'),taskPrioritySelect=$('taskPrioritySelect'),addTaskBtn=$('addTaskBtn');
const startBtn=$('startBtn'),openHistoryBtn=$('openHistoryBtn'),openSettingsBtn=$('openSettingsBtn'),statsOpenHistoryBtn=$('statsOpenHistoryBtn');
const pauseTimerBtn=$('pauseTimerBtn'),breakBtn=$('breakBtn'),endBreakBtn=$('endBreakBtn'),nextMsgBtn=$('nextMsgBtn'),leaveBtn=$('leaveBtn');
const toggleCamBtn=$('toggleCamBtn'),wakeLockBtn=$('wakeLockBtn'),fullscreenBtn=$('fullscreenBtn'),restartSessionBtn=$('restartSessionBtn');
const selfVideoThumb=$('selfVideoThumb'),selfVideoMain=$('selfVideoMain');
const soundModeSelect=$('soundModeSelect'),soundVolumeRange=$('soundVolumeRange'),soundToggleBtn=$('soundToggleBtn');
const goalTimer=$('goalTimer'),sessionType=$('sessionType'),focusScore=$('focusScore'),coachNameInline=$('coachNameInline'),coachStatePill=$('coachStatePill'),coachWidgetStatus=$('coachWidgetStatus'),monitoringText=$('monitoringText'),monitoringSubText=$('monitoringSubText'),teacherAlertText=$('teacherAlertText'),surveillanceBannerText=$('surveillanceBannerText');
const elapsedTime=$('elapsedTime'),dailyTotal=$('dailyTotal'),blurCountEl=$('blurCount'),completionRate=$('completionRate');
const activeTaskName=$('activeTaskName'),activeTaskMeta=$('activeTaskMeta'),watchState=$('watchState'),cameraStatus=$('cameraStatus');
const focusMessage=$('focusMessage'),weeklyTotal=$('weeklyTotal'),streakDays=$('streakDays'),breakCountEl=$('breakCount'),pauseCountEl=$('pauseCount'),dailyComparison=$('dailyComparison'),camOffTime=$('camOffTime'),launchMode=$('launchMode'),statsMonitorState=$('statsMonitorState'),statsTeacherAlert=$('statsTeacherAlert');
const tabActionsBtn=$('tabActionsBtn'),tabTasksBtn=$('tabTasksBtn'),tabRoomBtn=$('tabRoomBtn'),tabStatsBtn=$('tabStatsBtn');
const viewActions=$('viewActions'),viewTasks=$('viewTasks'),viewRoom=$('viewRoom'),viewStats=$('viewStats');
const settingsModal=$('settingsModal'),closeSettingsBtn=$('closeSettingsBtn'),modalGoalMinutesSelect=$('modalGoalMinutesSelect'),modalBreakMinutesSelect=$('modalBreakMinutesSelect'),modalCoachNameInput=$('modalCoachNameInput'),saveSettingsBtn=$('saveSettingsBtn');
const reportModal=$('reportModal'),reportBody=$('reportBody'),postNextGoalInput=$('postNextGoalInput'),saveNextGoalBtn=$('saveNextGoalBtn'),closeReportBtn=$('closeReportBtn'),copyReportBtn=$('copyReportBtn');
const historyModal=$('historyModal'),historyBody=$('historyBody'),closeHistoryBtn=$('closeHistoryBtn'),exportLogsBtn=$('exportLogsBtn');
const hiddenOverlay=$('hiddenOverlay');
const APP_CONFIG=window.APP_CONFIG||{},LIFF_ID=APP_CONFIG.LIFF_ID||"",ALLOW_NON_LIFF_MODE=APP_CONFIG.ALLOW_NON_LIFF_MODE!==false;
const STORAGE_KEYS={coachName:'focus-room-v17-coach-name',goalMinutes:'focus-room-v17-goal-minutes',breakMinutes:'focus-room-v17-break-minutes',nextGoal:'focus-room-v17-next-goal',tasks:'focus-room-v17-tasks',activeView:'focus-room-v17-active-view',sessions:'focus-room-v17-sessions',weeklyLogs:'focus-room-v17-weekly-logs',userWidgetPos:'focus-room-v17-user-widget-pos'};
let tasks=[],selectedGoalMinutes=25,selectedBreakMinutes=5,activeView='actions',stream=null,camEnabled=true,wakeLock=null,sessionStartedAt=null,elapsedInterval=null,timerInterval=null,messageInterval=null,monitorInterval=null,camOffInterval=null,blurCount=0,pauseCount=0,breakCount=0,camOffSeconds=0,timerPaused=false,onBreak=false,remainingSeconds=25*60,breakRemaining=0,currentSessionLog=null,audioContext=null,noiseNode=null,gainNode=null,toneOscillator=null;
const roomMessages=['今のタスクを1つだけ進めましょう。','迷ったら、いちばん小さい作業から始めましょう。','手が止まったら、30秒だけ続けましょう。','今やるべきタスクを1件だけ見て進めましょう。'],monitorTexts=['在席確認中','学習状況監視中','視線確認中','離席警戒中'],subMonitorTexts=['離席検知 有効','画面切替 検知中','カメラ監視 有効','集中確認 有効'],teacherAlerts=['このルームでは離席・画面切替・学習停止を前提に確認しながら進行します。','姿勢を整えて、今のタスクを続けてください。','手が止まっているなら、まずは1問だけ進めてください。','在席前提で進行しています。画面を前面に保ってください。'],bannerTexts=['このルームは在席確認つきで進行しています','離席検知と学習確認を前提に進行しています','監視前提の集中ルームです'];
const setStoredValue=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const getStoredValue=(k,d)=>{const r=localStorage.getItem(k);if(r===null)return d;try{return JSON.parse(r)}catch{return d}};
const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2,8)}`,randomFrom=(l)=>l[Math.floor(Math.random()*l.length)];
const escapeHtml=(v)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const formatClock=(s)=>`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const formatMinSec=(s)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function todayKey(o=0){const d=new Date();d.setDate(d.getDate()+o);return d.toISOString().slice(0,10)}
function loadDailyTotal(k=todayKey()){const r=localStorage.getItem(`focus-room-total-${k}`);return r?Number(r):0}
function saveDailyTotal(sec){localStorage.setItem(`focus-room-total-${todayKey()}`,String(sec));const min=Math.floor(sec/60);dailyTotal.textContent=`${String(Math.floor(min/60)).padStart(2,'0')}:${String(min%60).padStart(2,'0')}`}
function setCoachStatus(text){coachWidgetStatus.textContent=text}
function setMonitorText(text){monitoringText.textContent=text;statsMonitorState.textContent=text}
function setTeacherAlert(text){teacherAlertText.textContent=text;statsTeacherAlert.textContent=text}
function setBannerText(text){surveillanceBannerText.textContent=text}
function setSubMonitorText(text){monitoringSubText.textContent=text}
function updateMessage(force=false,txt=''){focusMessage.textContent=txt||randomFrom(roomMessages);if(force){focusMessage.animate([{opacity:.2,transform:'translateY(4px)'},{opacity:1,transform:'translateY(0)'}],{duration:260,easing:'ease-out'})}}
function applyPrejoinSummary(){prejoinGoalLabel.textContent=`${selectedGoalMinutes}分`;prejoinTaskCount.textContent=`${tasks.length}件`}
function sortTasks(list){const p={'高':0,'中':1,'低':2};return [...list].sort((a,b)=>{if(a.status==='進行中'&&b.status!=='進行中')return-1;if(a.status!=='進行中'&&b.status==='進行中')return 1;if(a.status==='完了'&&b.status!=='完了')return 1;if(a.status!=='完了'&&b.status==='完了')return-1;if(p[a.priority]!==p[b.priority])return p[a.priority]-p[b.priority];return a.createdAt-b.createdAt})}
const getActiveTask=()=>sortTasks(tasks).find(t=>t.status==='進行中')||null;
const getCompletionRate=()=>tasks.length===0?0:Math.round(tasks.filter(t=>t.status==='完了').length/tasks.length*100);
function updateActiveTaskBox(){const a=getActiveTask();if(!a){activeTaskName.textContent='まだありません';activeTaskMeta.textContent='進行中にしたタスクがここに表示されます。';return}activeTaskName.textContent=a.title;activeTaskMeta.textContent=`予定時間 ${a.estimate}分 / 優先度 ${a.priority} / 目標 ${a.goal}`}
function taskCardHtml(t){return `<div class="task-item"><div class="task-item-top"><div><div class="task-title">${escapeHtml(t.title)}</div><div class="task-meta">目標：${escapeHtml(t.goal)}</div><div class="task-extra">予定時間：${t.estimate}分 / 優先度：${escapeHtml(t.priority)}</div></div><span class="pill">${escapeHtml(t.status)}</span></div><div class="task-actions"><button class="btn btn-secondary" data-action="todo" data-id="${t.id}">未開始</button><button class="btn btn-secondary" data-action="doing" data-id="${t.id}">進行中</button><button class="btn btn-secondary" data-action="done" data-id="${t.id}">完了</button><button class="btn btn-secondary" data-action="delete" data-id="${t.id}">削除</button></div></div>`}
function renderTasks(){const s=sortTasks(tasks);taskSummaryCount.textContent=`${tasks.length}件`;roomTaskCount.textContent=`${tasks.length}件`;prejoinTaskList.innerHTML=s.length?s.map(t=>`<div class="task-item"><div class="task-title">${escapeHtml(t.title)}</div><div class="task-meta">目標：${escapeHtml(t.goal)}</div></div>`).join(''):'<p class="empty-text">まだタスクがありません。</p>';roomTaskList.innerHTML=s.length?s.map(taskCardHtml).join(''):'<p class="empty-text">タスクがありません。</p>';completionRate.textContent=`${getCompletionRate()}%`;updateActiveTaskBox();applyPrejoinSummary()}
function addTask(){const title=taskTitleInput.value.trim(),goal=taskGoalInput.value.trim(),estimate=Number(taskEstimateSelect.value||30),priority=taskPrioritySelect.value||'高';if(!title){alert('タスク名を入力してください。');return}tasks.push({id:uid(),title,goal:goal||'未設定',estimate,priority,status:'未開始',createdAt:Date.now()});setStoredValue(STORAGE_KEYS.tasks,tasks);taskTitleInput.value='';taskGoalInput.value='';taskEstimateSelect.value='30';taskPrioritySelect.value='高';renderTasks()}
function updateTaskStatus(id,status){tasks=tasks.map(t=>t.id===id?{...t,status}:t);setStoredValue(STORAGE_KEYS.tasks,tasks);renderTasks()}
function deleteTask(id){tasks=tasks.filter(t=>t.id!==id);setStoredValue(STORAGE_KEYS.tasks,tasks);renderTasks()}
function bindTaskActions(){roomTaskList.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const id=b.dataset.id,a=b.dataset.action;if(a==='todo')updateTaskStatus(id,'未開始');if(a==='doing')updateTaskStatus(id,'進行中');if(a==='done')updateTaskStatus(id,'完了');if(a==='delete')deleteTask(id)})}
function applyPrejoinSettings(save=true){selectedGoalMinutes=Number(goalMinutesSelect.value||25);selectedBreakMinutes=Number(breakMinutesSelect.value||5);if(save){setStoredValue(STORAGE_KEYS.goalMinutes,selectedGoalMinutes);setStoredValue(STORAGE_KEYS.breakMinutes,selectedBreakMinutes);setStoredValue(STORAGE_KEYS.coachName,coachNameInput.value.trim()||'SENSEI ROOM')}coachNameInline.textContent=coachNameInput.value.trim()||'SENSEI ROOM';goalTimer.textContent=formatMinSec(selectedGoalMinutes*60);applyPrejoinSummary()}
function loadSavedState(){selectedGoalMinutes=getStoredValue(STORAGE_KEYS.goalMinutes,25);selectedBreakMinutes=getStoredValue(STORAGE_KEYS.breakMinutes,5);goalMinutesSelect.value=String(selectedGoalMinutes);breakMinutesSelect.value=String(selectedBreakMinutes);coachNameInput.value=getStoredValue(STORAGE_KEYS.coachName,'SENSEI ROOM');modalGoalMinutesSelect.value=String(selectedGoalMinutes);modalBreakMinutesSelect.value=String(selectedBreakMinutes);modalCoachNameInput.value=coachNameInput.value;postNextGoalInput.value=nextGoalInput.value;tasks=getStoredValue(STORAGE_KEYS.tasks,[]);activeView=getStoredValue(STORAGE_KEYS.activeView,'actions')}
function applyRoomView(){const map={actions:[viewActions,tabActionsBtn],tasks:[viewTasks,tabTasksBtn],room:[viewRoom,tabRoomBtn],stats:[viewStats,tabStatsBtn]};Object.entries(map).forEach(([k,[v,b]])=>{const a=k===activeView;v.classList.toggle('active',a);b.classList.toggle('active',a)});setStoredValue(STORAGE_KEYS.activeView,activeView)}
const openRoomView=(n)=>{activeView=n;applyRoomView()}
const getWeeklyLogs=()=>getStoredValue(STORAGE_KEYS.weeklyLogs,{});
const setWeeklyLogs=(logs)=>setStoredValue(STORAGE_KEYS.weeklyLogs,logs);
function updateWeeklyStats(){const logs=getWeeklyLogs(),days=Array.from({length:7},(_,i)=>todayKey(-i)),total=days.reduce((s,k)=>s+(logs[k]?.minutes||0),0);weeklyTotal.textContent=`${total}分`;const diff=Math.round((loadDailyTotal(todayKey())-loadDailyTotal(todayKey(-1)))/60);dailyComparison.textContent=`${diff>=0?'+':''}${diff}分`;let streak=0;for(let i=0;i<30;i++){const mins=logs[todayKey(-i)]?.minutes||0;if(mins>0)streak++;else break}streakDays.textContent=`${streak}日`}
function updateFocusScore(){let score=100;score-=blurCount*8;score-=pauseCount*5;score-=breakCount*3;score-=Math.floor(camOffSeconds/30)*4;score=Math.max(0,Math.min(100,score));focusScore.textContent=String(score)}
function recordWeeklyMinutes(){const logs=getWeeklyLogs();logs[todayKey()]={minutes:Math.round(loadDailyTotal(todayKey())/60),updatedAt:Date.now()};setWeeklyLogs(logs);updateWeeklyStats()}
function updateCountersUI(){breakCountEl.textContent=String(breakCount);pauseCountEl.textContent=String(pauseCount);camOffTime.textContent=`${camOffSeconds}秒`;blurCountEl.textContent=String(blurCount);updateFocusScore()}
function clearTimers(){clearInterval(elapsedInterval);clearInterval(timerInterval);clearInterval(messageInterval);clearInterval(monitorInterval);clearInterval(camOffInterval)}
function setRoomButtonsStarted(started){toggleCamBtn.disabled=!started;pauseTimerBtn.disabled=!started;breakBtn.disabled=!started||onBreak;endBreakBtn.disabled=!started||!onBreak}
function startMonitorEffects(){clearInterval(monitorInterval);monitorInterval=setInterval(()=>{setMonitorText(randomFrom(monitorTexts));setSubMonitorText(randomFrom(subMonitorTexts));setTeacherAlert(randomFrom(teacherAlerts));setBannerText(randomFrom(bannerTexts))},8000)}
function startCamOffCounter(){clearInterval(camOffInterval);camOffInterval=setInterval(()=>{if(stream&&!camEnabled){camOffSeconds+=1;updateCountersUI()}},1000)}
function playNotification(){try{const ctx=audioContext||new(window.AudioContext||window.webkitAudioContext)();audioContext=ctx;const osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=880;gain.gain.value=.02;osc.start();osc.stop(ctx.currentTime+.2)}catch{}}
function startRoomTimers(resetElapsed=true){clearTimers();if(resetElapsed||!sessionStartedAt)sessionStartedAt=Date.now();timerPaused=false;pauseTimerBtn.textContent='一時停止';const baseline=loadDailyTotal();saveDailyTotal(baseline);elapsedInterval=setInterval(()=>{if(timerPaused)return;const sec=Math.floor((Date.now()-sessionStartedAt)/1000);elapsedTime.textContent=formatClock(sec);if(!onBreak){saveDailyTotal(baseline+sec);recordWeeklyMinutes()}},1000);timerInterval=setInterval(()=>{if(timerPaused)return;if(onBreak){breakRemaining-=1;goalTimer.textContent=formatMinSec(breakRemaining);if(breakRemaining<=0){playNotification();endBreak()}return}remainingSeconds-=1;goalTimer.textContent=formatMinSec(remainingSeconds);if(remainingSeconds<=0){remainingSeconds=0;goalTimer.textContent=formatMinSec(remainingSeconds);sessionType.textContent='目標到達';setCoachStatus('学習時間に到達');setMonitorText('確認強化中');setTeacherAlert('目標時間に到達しました。離席せず、進み具合を確認してください。');setBannerText('学習時間到達後も在席確認を継続しています');updateMessage(true,'目標時間に到達しました。進み具合を確認しましょう。')}},1000);messageInterval=setInterval(()=>{if(!timerPaused)updateMessage(true)},60000);startMonitorEffects();startCamOffCounter()}
function beginSessionLog(){currentSessionLog={id:uid(),startedAt:new Date().toISOString(),goalMinutes:selectedGoalMinutes,nextGoal:getStoredValue(STORAGE_KEYS.nextGoal,'')||'',blurCount:0,pauseCount:0,breakCount:0,camOffSeconds:0,tasks:tasks.map(t=>({title:t.title,status:t.status,estimate:t.estimate,priority:t.priority}))}}
function finalizeSessionLog(){if(!currentSessionLog)return null;currentSessionLog.endedAt=new Date().toISOString();currentSessionLog.dailyTotalMinutes=Math.round(loadDailyTotal(todayKey())/60);currentSessionLog.blurCount=blurCount;currentSessionLog.pauseCount=pauseCount;currentSessionLog.breakCount=breakCount;currentSessionLog.camOffSeconds=camOffSeconds;currentSessionLog.focusScore=Number(focusScore.textContent||'0');currentSessionLog.completionRate=getCompletionRate();currentSessionLog.tasks=tasks.map(t=>({title:t.title,status:t.status,estimate:t.estimate,priority:t.priority}));const sessions=getStoredValue(STORAGE_KEYS.sessions,[]);sessions.unshift(currentSessionLog);setStoredValue(STORAGE_KEYS.sessions,sessions.slice(0,50));return currentSessionLog}
function renderReport(log){if(!log)return;const done=log.tasks.filter(t=>t.status==='完了').length;reportBody.innerHTML=`<div class="report-item"><strong>集中スコア</strong><div>${log.focusScore}</div></div><div class="report-item"><strong>達成率</strong><div>${log.completionRate}%（完了 ${done}/${log.tasks.length}）</div></div><div class="report-item"><strong>離席 / 停止 / 休憩</strong><div>離席 ${log.blurCount}回 / 停止 ${log.pauseCount}回 / 休憩 ${log.breakCount}回</div></div><div class="report-item"><strong>カメラ停止時間</strong><div>${log.camOffSeconds}秒</div></div>`;postNextGoalInput.value=getStoredValue(STORAGE_KEYS.nextGoal,'');reportModal.classList.remove('hidden')}
function renderHistory(){const sessions=getStoredValue(STORAGE_KEYS.sessions,[]);historyBody.innerHTML=sessions.length?sessions.map(s=>`<div class="history-item"><strong>${new Date(s.startedAt).toLocaleString('ja-JP')}</strong><div>集中スコア ${s.focusScore} / 達成率 ${s.completionRate}% / 離席 ${s.blurCount}回</div></div>`).join(''):'<p class="empty-text">履歴はまだありません。</p>';historyModal.classList.remove('hidden')}
function exportLogs(){const data={sessions:getStoredValue(STORAGE_KEYS.sessions,[]),weekly:getWeeklyLogs(),tasks};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='focus-room-log.json';a.click();URL.revokeObjectURL(a.href)}
async function ensureAudioContext(){if(!audioContext){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)throw new Error('unsupported');audioContext=new Ctx()}if(audioContext.state==='suspended')await audioContext.resume()}
function createNoiseBuffer(ctx,type='white'){const size=2*ctx.sampleRate,buffer=ctx.createBuffer(1,size,ctx.sampleRate),out=buffer.getChannelData(0);let last=0;for(let i=0;i<size;i++){const white=Math.random()*2-1;if(type==='brown'){out[i]=(last+.02*white)/1.02;last=out[i];out[i]*=3.5}else out[i]=white}return buffer}
async function toggleSound(){const mode=soundModeSelect.value;if(mode==='off'){stopSound();return}if(noiseNode||toneOscillator){stopSound();return}await ensureAudioContext();gainNode=audioContext.createGain();gainNode.gain.value=Number(soundVolumeRange.value)/1000;gainNode.connect(audioContext.destination);if(mode==='tone'){toneOscillator=audioContext.createOscillator();toneOscillator.type='sine';toneOscillator.frequency.value=180;toneOscillator.connect(gainNode);toneOscillator.start()}else{noiseNode=audioContext.createBufferSource();noiseNode.buffer=createNoiseBuffer(audioContext,mode);noiseNode.loop=true;noiseNode.connect(gainNode);noiseNode.start()}soundToggleBtn.textContent='サウンド停止'}
function stopSound(){try{noiseNode?.stop?.()}catch{}try{toneOscillator?.stop?.()}catch{}noiseNode=null;toneOscillator=null;gainNode?.disconnect?.();gainNode=null;soundToggleBtn.textContent='サウンド開始'}
const updateSoundVolume=()=>{if(gainNode)gainNode.gain.value=Number(soundVolumeRange.value)/1000}
async function startCamera(){if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){alert('このブラウザではカメラ取得に対応していません。');return}applyPrejoinSettings(true);if(tasks.length===0){alert('先にタスクを1件以上追加してください。');return}beginSessionLog();try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});selfVideoThumb.srcObject=stream;selfVideoMain.srcObject=stream;prejoinScreen.classList.remove('active');roomScreen.classList.add('active');userWidget.classList.remove('hidden');cameraStatus.textContent='稼働中';watchState.textContent='入室中';coachStatePill.textContent='監視中';sessionType.textContent=`${selectedGoalMinutes}分の学習中`;setCoachStatus('学習状況を確認しています');setMonitorText('在席確認中');setSubMonitorText('離席検知 有効');setTeacherAlert('このルームでは離席・画面切替・学習停止を前提に確認しながら進行します。');setBannerText('このルームは在席確認つきで進行しています');startBtn.disabled=true;setRoomButtonsStarted(true);camEnabled=true;toggleCamBtn.textContent='カメラ停止';onBreak=false;remainingSeconds=selectedGoalMinutes*60;goalTimer.textContent=formatMinSec(remainingSeconds);const firstTodo=sortTasks(tasks).find(t=>t.status==='未開始');if(firstTodo)updateTaskStatus(firstTodo.id,'進行中');startRoomTimers(true);updateMessage(true,'入室しました。今日のタスクを進めましょう。');openRoomView(activeView)}catch(e){console.error(e);alert('カメラ許可が必要です。ブラウザの権限を確認してください。')}}
function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());selfVideoThumb.srcObject=null;selfVideoMain.srcObject=null;stream=null;cameraStatus.textContent='待機中';watchState.textContent='待機中';coachStatePill.textContent='接続中';sessionType.textContent='未開始';setCoachStatus('ルーム待機中');setMonitorText('在席確認前');setSubMonitorText('離席検知 有効');setTeacherAlert('目標時間を設定して、今日のタスクを追加してから入室してください。');setBannerText('このルームは在席確認つきで進行しています');startBtn.disabled=false;setRoomButtonsStarted(false);breakBtn.disabled=true;endBreakBtn.disabled=true;onBreak=false;clearTimers();roomScreen.classList.remove('active');prejoinScreen.classList.add('active');userWidget.classList.add('hidden');const log=finalizeSessionLog();if(log)renderReport(log)}
function toggleCameraEnabled(){if(!stream)return;const track=stream.getVideoTracks()[0];if(!track)return;camEnabled=!camEnabled;track.enabled=camEnabled;toggleCamBtn.textContent=camEnabled?'カメラ停止':'カメラ再開';cameraStatus.textContent=camEnabled?'稼働中':'一時停止';setMonitorText(camEnabled?'映像確認中':'映像停止中');setSubMonitorText(camEnabled?'離席検知 有効':'映像停止 記録中')}
function toggleTimerPause(){if(!stream)return;timerPaused=!timerPaused;pauseCount+=1;pauseTimerBtn.textContent=timerPaused?'再開':'一時停止';setCoachStatus(timerPaused?'一時停止中':'学習状況を確認しています');setMonitorText(timerPaused?'確認待機中':'在席確認中');updateCountersUI();updateMessage(true,timerPaused?'タイマーを一時停止しました。':'タイマーを再開しました。')}
function startBreak(){if(!stream||onBreak)return;onBreak=true;breakCount+=1;breakRemaining=selectedBreakMinutes*60;sessionType.textContent='休憩中';breakBtn.disabled=true;endBreakBtn.disabled=false;setCoachStatus('休憩中');setMonitorText('休憩確認中');setTeacherAlert('休憩中です。戻ったらすぐに学習を再開してください。');setBannerText('休憩中も在席状態の確認を継続しています');updateCountersUI();playNotification();updateMessage(true,'休憩に入りました。戻ったら「休憩終了」を押してください。')}
function endBreak(){if(!stream||!onBreak)return;onBreak=false;sessionType.textContent=`${selectedGoalMinutes}分の学習中`;breakBtn.disabled=false;endBreakBtn.disabled=true;setCoachStatus('学習状況を確認しています');setMonitorText('在席確認中');setTeacherAlert('休憩終了です。姿勢を整えて学習を再開してください。');setBannerText('このルームは在席確認つきで進行しています');playNotification();updateMessage(true,'休憩を終了しました。学習を再開しましょう。')}
function restartSessionFromSettings(){selectedGoalMinutes=Number(modalGoalMinutesSelect.value||selectedGoalMinutes);selectedBreakMinutes=Number(modalBreakMinutesSelect.value||selectedBreakMinutes);coachNameInline.textContent=modalCoachNameInput.value.trim()||'SENSEI ROOM';elapsedTime.textContent='00:00:00';sessionStartedAt=Date.now();onBreak=false;breakBtn.disabled=!stream;endBreakBtn.disabled=true;remainingSeconds=selectedGoalMinutes*60;goalTimer.textContent=formatMinSec(remainingSeconds);if(stream){sessionType.textContent=`${selectedGoalMinutes}分の学習中`;setCoachStatus('学習状況を確認しています');setMonitorText('在席確認中');setTeacherAlert('設定を更新しました。このまま学習を継続してください。');startRoomTimers(true);updateMessage(true,'設定内容でセッションを再開始しました。')}}
async function requestFullscreen(){const el=document.documentElement;if(!document.fullscreenElement)await el.requestFullscreen?.();else await document.exitFullscreen?.()}
async function requestWakeLock(){if(!('wakeLock' in navigator)){alert('この端末では画面スリープ防止に未対応です。');return}try{wakeLock=await navigator.wakeLock.request('screen');wakeLockBtn.textContent='防止中';wakeLock.addEventListener('release',()=>wakeLockBtn.textContent='スリープ防止')}catch(e){console.error(e);alert('画面スリープ防止を有効にできませんでした。')}}
async function initLiffApp(){if(!window.liff||!LIFF_ID){lineProfileName.textContent='通常ブラウザで利用中';launchMode.textContent='通常ブラウザ';return}try{await liff.init({liffId:LIFF_ID});launchMode.textContent=liff.isInClient()?'LINE内ブラウザ':'外部ブラウザ';if(!liff.isLoggedIn()){if(ALLOW_NON_LIFF_MODE){lineProfileName.textContent='ログインなしで利用中';return}liff.login();return}const p=await liff.getProfile();lineProfileName.textContent=`${p.displayName} さん`}catch(e){console.error(e);lineProfileName.textContent='ユーザー情報の取得に失敗しました'}}
function clamp(v,min,max){return Math.min(Math.max(v,min),max)}
function applyUserWidgetPosition(x,y,save=true){const margin=8,maxX=window.innerWidth-userWidget.offsetWidth-margin,maxY=window.innerHeight-userWidget.offsetHeight-margin,fx=clamp(x,margin,maxX),fy=clamp(y,margin,maxY);userWidget.style.left=`${fx}px`;userWidget.style.top=`${fy}px`;userWidget.style.right='auto';if(save)setStoredValue(STORAGE_KEYS.userWidgetPos,{x:fx,y:fy})}
function restoreUserWidgetPosition(){const saved=getStoredValue(STORAGE_KEYS.userWidgetPos,null);if(saved&&typeof saved.x==='number'&&typeof saved.y==='number')applyUserWidgetPosition(saved.x,saved.y,false);else applyUserWidgetPosition(window.innerWidth-userWidget.offsetWidth-12,12,false)}
function initDragWidget(){let sx=0,sy=0,ox=0,oy=0,drag=false;const mv=e=>{if(!drag)return;applyUserWidgetPosition(ox+(e.clientX-sx),oy+(e.clientY-sy),false)},up=()=>{if(!drag)return;drag=false;const r=userWidget.getBoundingClientRect(),tx=r.left<window.innerWidth/2?8:window.innerWidth-r.width-8;applyUserWidgetPosition(tx,r.top,true);window.removeEventListener('pointermove',mv);window.removeEventListener('pointerup',up)};userWidgetHandle.addEventListener('pointerdown',e=>{drag=true;sx=e.clientX;sy=e.clientY;const r=userWidget.getBoundingClientRect();ox=r.left;oy=r.top;window.addEventListener('pointermove',mv);window.addEventListener('pointerup',up)})}
goalMinutesSelect.addEventListener('change',()=>{selectedGoalMinutes=Number(goalMinutesSelect.value);applyPrejoinSettings(false)});breakMinutesSelect.addEventListener('change',()=>{selectedBreakMinutes=Number(breakMinutesSelect.value);applyPrejoinSettings(false)});coachNameInput.addEventListener('input',()=>applyPrejoinSettings(false));addTaskBtn.addEventListener('click',addTask);startBtn.addEventListener('click',startCamera);
tabActionsBtn.addEventListener('click',()=>openRoomView('actions'));tabTasksBtn.addEventListener('click',()=>openRoomView('tasks'));tabRoomBtn.addEventListener('click',()=>openRoomView('room'));tabStatsBtn.addEventListener('click',()=>openRoomView('stats'));
openHistoryBtn.addEventListener('click',renderHistory);statsOpenHistoryBtn.addEventListener('click',renderHistory);closeHistoryBtn.addEventListener('click',()=>historyModal.classList.add('hidden'));exportLogsBtn.addEventListener('click',exportLogs);
openSettingsBtn.addEventListener('click',()=>{modalGoalMinutesSelect.value=String(selectedGoalMinutes);modalBreakMinutesSelect.value=String(selectedBreakMinutes);modalCoachNameInput.value=coachNameInline.textContent;settingsModal.classList.remove('hidden')});closeSettingsBtn.addEventListener('click',()=>settingsModal.classList.add('hidden'));saveSettingsBtn.addEventListener('click',()=>{selectedGoalMinutes=Number(modalGoalMinutesSelect.value||25);selectedBreakMinutes=Number(modalBreakMinutesSelect.value||5);coachNameInline.textContent=modalCoachNameInput.value.trim()||'SENSEI ROOM';setStoredValue(STORAGE_KEYS.goalMinutes,selectedGoalMinutes);setStoredValue(STORAGE_KEYS.breakMinutes,selectedBreakMinutes);setStoredValue(STORAGE_KEYS.coachName,coachNameInline.textContent);goalMinutesSelect.value=String(selectedGoalMinutes);breakMinutesSelect.value=String(selectedBreakMinutes);coachNameInput.value=coachNameInline.textContent;applyPrejoinSummary();settingsModal.classList.add('hidden');restartSessionFromSettings()});
pauseTimerBtn.addEventListener('click',toggleTimerPause);breakBtn.addEventListener('click',startBreak);endBreakBtn.addEventListener('click',endBreak);nextMsgBtn.addEventListener('click',()=>{setTeacherAlert(randomFrom(teacherAlerts));setBannerText(randomFrom(bannerTexts));updateMessage(true)});leaveBtn.addEventListener('click',()=>{stopCamera();if(document.fullscreenElement)document.exitFullscreen?.();alert('退出しました。おつかれさまでした。')});toggleCamBtn.addEventListener('click',toggleCameraEnabled);wakeLockBtn.addEventListener('click',requestWakeLock);fullscreenBtn.addEventListener('click',requestFullscreen);restartSessionBtn.addEventListener('click',restartSessionFromSettings);
soundToggleBtn.addEventListener('click',toggleSound);soundModeSelect.addEventListener('change',stopSound);soundVolumeRange.addEventListener('input',updateSoundVolume);
saveNextGoalBtn.addEventListener('click',()=>{const v=postNextGoalInput.value.trim();setStoredValue(STORAGE_KEYS.nextGoal,v);applyPrejoinSummary();alert('次回目標を保存しました。')});closeReportBtn.addEventListener('click',()=>reportModal.classList.add('hidden'));copyReportBtn.addEventListener('click',async()=>{await navigator.clipboard.writeText(reportBody.innerText);alert('レポートをコピーしました。')});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&roomScreen.classList.contains('active')){blurCount+=1;updateCountersUI();hiddenOverlay.classList.remove('hidden');setMonitorText('離席検知');setSubMonitorText('警告表示中');setTeacherAlert('画面から離れています。すぐに戻って学習を再開してください。');setBannerText('離席検知中です。画面へ戻ってください');updateMessage(true,'この画面に戻って、そのまま学習を続けましょう。')}else{hiddenOverlay.classList.add('hidden');if(stream&&!timerPaused&&!onBreak){setMonitorText('在席確認中');setSubMonitorText('離席検知 有効')}}});
document.addEventListener('visibilitychange',async()=>{if(wakeLock!==null&&document.visibilityState==='visible'){try{wakeLock=await navigator.wakeLock.request('screen')}catch{}}});
document.addEventListener('fullscreenchange',()=>{fullscreenBtn.textContent=document.fullscreenElement?'解除':'フルスクリーン'});window.addEventListener('beforeunload',e=>{if(stream){e.preventDefault();e.returnValue=''}});window.addEventListener('resize',()=>{const r=userWidget.getBoundingClientRect();applyUserWidgetPosition(r.left,r.top,true)});
window.addEventListener('DOMContentLoaded',async()=>{loadSavedState();bindTaskActions();applyPrejoinSettings(false);renderTasks();updateWeeklyStats();updateCountersUI();applyRoomView();restoreUserWidgetPosition();initDragWidget();setCoachStatus('学習状況を確認しています');setMonitorText('在席確認前');setSubMonitorText('離席検知 有効');setTeacherAlert('このルームでは離席・画面切替・学習停止を前提に確認しながら進行します。');setBannerText('このルームは在席確認つきで進行しています');saveDailyTotal(loadDailyTotal());await initLiffApp()});
